# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DoIP.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFormLayout,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QTabWidget, QTextBrowser,
    QTextEdit, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1037, 804)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 1021, 491))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.pushButton_undefined_3 = QPushButton(self.tab_9)
        self.pushButton_undefined_3.setObjectName(u"pushButton_undefined_3")
        self.pushButton_undefined_3.setGeometry(QRect(170, 190, 79, 31))
        self.pushButton_undefined_9 = QPushButton(self.tab_9)
        self.pushButton_undefined_9.setObjectName(u"pushButton_undefined_9")
        self.pushButton_undefined_9.setGeometry(QRect(170, 370, 79, 31))
        self.pushButton_undefined_2 = QPushButton(self.tab_9)
        self.pushButton_undefined_2.setObjectName(u"pushButton_undefined_2")
        self.pushButton_undefined_2.setGeometry(QRect(170, 160, 79, 31))
        self.pushButton_undefined_8 = QPushButton(self.tab_9)
        self.pushButton_undefined_8.setObjectName(u"pushButton_undefined_8")
        self.pushButton_undefined_8.setGeometry(QRect(170, 340, 79, 31))
        self.pushButton_undefined_4 = QPushButton(self.tab_9)
        self.pushButton_undefined_4.setObjectName(u"pushButton_undefined_4")
        self.pushButton_undefined_4.setGeometry(QRect(170, 220, 79, 31))
        self.pushButton_undefined_6 = QPushButton(self.tab_9)
        self.pushButton_undefined_6.setObjectName(u"pushButton_undefined_6")
        self.pushButton_undefined_6.setGeometry(QRect(170, 280, 79, 31))
        self.pushButton_undefined_1 = QPushButton(self.tab_9)
        self.pushButton_undefined_1.setObjectName(u"pushButton_undefined_1")
        self.pushButton_undefined_1.setGeometry(QRect(170, 130, 79, 31))
        self.pushButton_undefined_10 = QPushButton(self.tab_9)
        self.pushButton_undefined_10.setObjectName(u"pushButton_undefined_10")
        self.pushButton_undefined_10.setGeometry(QRect(170, 400, 79, 31))
        self.pushButton_undefined_7 = QPushButton(self.tab_9)
        self.pushButton_undefined_7.setObjectName(u"pushButton_undefined_7")
        self.pushButton_undefined_7.setGeometry(QRect(170, 310, 79, 31))
        self.pushButton_undefined_5 = QPushButton(self.tab_9)
        self.pushButton_undefined_5.setObjectName(u"pushButton_undefined_5")
        self.pushButton_undefined_5.setGeometry(QRect(170, 250, 79, 31))
        self.pushButton_undefined_11 = QPushButton(self.tab_9)
        self.pushButton_undefined_11.setObjectName(u"pushButton_undefined_11")
        self.pushButton_undefined_11.setGeometry(QRect(300, 130, 79, 31))
        self.pushButton_undefined_12 = QPushButton(self.tab_9)
        self.pushButton_undefined_12.setObjectName(u"pushButton_undefined_12")
        self.pushButton_undefined_12.setGeometry(QRect(300, 160, 79, 31))
        self.pushButton_undefined_13 = QPushButton(self.tab_9)
        self.pushButton_undefined_13.setObjectName(u"pushButton_undefined_13")
        self.pushButton_undefined_13.setGeometry(QRect(300, 190, 79, 31))
        self.pushButton_undefined_14 = QPushButton(self.tab_9)
        self.pushButton_undefined_14.setObjectName(u"pushButton_undefined_14")
        self.pushButton_undefined_14.setGeometry(QRect(300, 220, 79, 31))
        self.pushButton_undefined_15 = QPushButton(self.tab_9)
        self.pushButton_undefined_15.setObjectName(u"pushButton_undefined_15")
        self.pushButton_undefined_15.setGeometry(QRect(300, 250, 79, 31))
        self.pushButton_undefined_16 = QPushButton(self.tab_9)
        self.pushButton_undefined_16.setObjectName(u"pushButton_undefined_16")
        self.pushButton_undefined_16.setGeometry(QRect(300, 280, 79, 31))
        self.pushButton_undefined_17 = QPushButton(self.tab_9)
        self.pushButton_undefined_17.setObjectName(u"pushButton_undefined_17")
        self.pushButton_undefined_17.setGeometry(QRect(300, 310, 79, 31))
        self.pushButton_undefined_18 = QPushButton(self.tab_9)
        self.pushButton_undefined_18.setObjectName(u"pushButton_undefined_18")
        self.pushButton_undefined_18.setGeometry(QRect(300, 340, 79, 31))
        self.pushButton_undefined_19 = QPushButton(self.tab_9)
        self.pushButton_undefined_19.setObjectName(u"pushButton_undefined_19")
        self.pushButton_undefined_19.setGeometry(QRect(300, 370, 79, 31))
        self.pushButton_undefined_20 = QPushButton(self.tab_9)
        self.pushButton_undefined_20.setObjectName(u"pushButton_undefined_20")
        self.pushButton_undefined_20.setGeometry(QRect(300, 400, 79, 31))
        self.label_120 = QLabel(self.tab_9)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setGeometry(QRect(70, 140, 101, 20))
        self.label_121 = QLabel(self.tab_9)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setGeometry(QRect(60, 400, 101, 20))
        self.label_122 = QLabel(self.tab_9)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(380, 140, 111, 20))
        self.label_123 = QLabel(self.tab_9)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setGeometry(QRect(380, 410, 111, 20))
        self.tabWidget.addTab(self.tab_9, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_extendedDiagnosticSession = QPushButton(self.tab)
        self.pushButton_extendedDiagnosticSession.setObjectName(u"pushButton_extendedDiagnosticSession")
        self.pushButton_extendedDiagnosticSession.setGeometry(QRect(160, 100, 181, 31))
        self.pushButton_defaultSession = QPushButton(self.tab)
        self.pushButton_defaultSession.setObjectName(u"pushButton_defaultSession")
        self.pushButton_defaultSession.setGeometry(QRect(160, 70, 181, 31))
        self.pushButton_hardReset = QPushButton(self.tab)
        self.pushButton_hardReset.setObjectName(u"pushButton_hardReset")
        self.pushButton_hardReset.setGeometry(QRect(160, 140, 181, 31))
        self.pushButton_softReset = QPushButton(self.tab)
        self.pushButton_softReset.setObjectName(u"pushButton_softReset")
        self.pushButton_softReset.setGeometry(QRect(160, 170, 181, 31))
        self.pushButton_SecurityAccess = QPushButton(self.tab)
        self.pushButton_SecurityAccess.setObjectName(u"pushButton_SecurityAccess")
        self.pushButton_SecurityAccess.setGeometry(QRect(40, 220, 171, 31))
        self.pushButton_13 = QPushButton(self.tab)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(40, 270, 171, 31))
        self.pushButton_ControlDTCSetting_Off = QPushButton(self.tab)
        self.pushButton_ControlDTCSetting_Off.setObjectName(u"pushButton_ControlDTCSetting_Off")
        self.pushButton_ControlDTCSetting_Off.setGeometry(QRect(220, 390, 41, 31))
        self.pushButton_ControlDTCSetting_On = QPushButton(self.tab)
        self.pushButton_ControlDTCSetting_On.setObjectName(u"pushButton_ControlDTCSetting_On")
        self.pushButton_ControlDTCSetting_On.setGeometry(QRect(220, 360, 41, 31))
        self.pushButton_ControlDTCSetting = QPushButton(self.tab)
        self.pushButton_ControlDTCSetting.setObjectName(u"pushButton_ControlDTCSetting")
        self.pushButton_ControlDTCSetting.setGeometry(QRect(40, 320, 171, 31))
        self.pushButton_TesterPresent = QPushButton(self.tab)
        self.pushButton_TesterPresent.setObjectName(u"pushButton_TesterPresent")
        self.pushButton_TesterPresent.setGeometry(QRect(40, 370, 171, 41))
        self.pushButton_ControlDTCSetting_On_2 = QPushButton(self.tab)
        self.pushButton_ControlDTCSetting_On_2.setObjectName(u"pushButton_ControlDTCSetting_On_2")
        self.pushButton_ControlDTCSetting_On_2.setGeometry(QRect(650, 70, 231, 31))
        self.pushButton_ReadDTCInformation = QPushButton(self.tab)
        self.pushButton_ReadDTCInformation.setObjectName(u"pushButton_ReadDTCInformation")
        self.pushButton_ReadDTCInformation.setGeometry(QRect(490, 70, 141, 51))
        self.pushButton_ControlDTCSetting_Off_2 = QPushButton(self.tab)
        self.pushButton_ControlDTCSetting_Off_2.setObjectName(u"pushButton_ControlDTCSetting_Off_2")
        self.pushButton_ControlDTCSetting_Off_2.setGeometry(QRect(650, 100, 181, 31))
        self.pushButton_stopRoutine = QPushButton(self.tab)
        self.pushButton_stopRoutine.setObjectName(u"pushButton_stopRoutine")
        self.pushButton_stopRoutine.setGeometry(QRect(650, 190, 171, 31))
        self.pushButton_RequestRoutineResults = QPushButton(self.tab)
        self.pushButton_RequestRoutineResults.setObjectName(u"pushButton_RequestRoutineResults")
        self.pushButton_RequestRoutineResults.setGeometry(QRect(650, 220, 171, 31))
        self.pushButton_StartRoutine = QPushButton(self.tab)
        self.pushButton_StartRoutine.setObjectName(u"pushButton_StartRoutine")
        self.pushButton_StartRoutine.setGeometry(QRect(650, 160, 171, 31))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 210, 61, 16))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 360, 53, 15))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 310, 53, 15))
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 260, 53, 15))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(500, 60, 53, 15))
        self.label_66 = QLabel(self.tab)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(50, 80, 91, 41))
        self.label_67 = QLabel(self.tab)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(350, 80, 53, 15))
        self.label_68 = QLabel(self.tab)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(350, 110, 53, 15))
        self.label_69 = QLabel(self.tab)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(50, 140, 91, 41))
        self.label_70 = QLabel(self.tab)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(350, 150, 53, 15))
        self.label_71 = QLabel(self.tab)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(350, 180, 53, 15))
        self.comboBox_CommunicationControl = QComboBox(self.tab)
        self.comboBox_CommunicationControl.setObjectName(u"comboBox_CommunicationControl")
        self.comboBox_CommunicationControl.setGeometry(QRect(350, 270, 131, 23))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 260, 111, 16))
        self.label_72 = QLabel(self.tab)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(220, 280, 111, 16))
        self.comboBox_routine_did = QComboBox(self.tab)
        self.comboBox_routine_did.setObjectName(u"comboBox_routine_did")
        self.comboBox_routine_did.setGeometry(QRect(820, 190, 191, 31))
        self.label_73 = QLabel(self.tab)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(500, 190, 131, 31))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(230, 210, 61, 16))
        self.pushButton_SecurityAccess_0506 = QPushButton(self.tab)
        self.pushButton_SecurityAccess_0506.setObjectName(u"pushButton_SecurityAccess_0506")
        self.pushButton_SecurityAccess_0506.setGeometry(QRect(220, 220, 171, 31))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_f187 = QPushButton(self.tab_2)
        self.pushButton_f187.setObjectName(u"pushButton_f187")
        self.pushButton_f187.setGeometry(QRect(150, 50, 201, 41))
        self.pushButton_f189 = QPushButton(self.tab_2)
        self.pushButton_f189.setObjectName(u"pushButton_f189")
        self.pushButton_f189.setGeometry(QRect(100, 90, 251, 41))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(350, 110, 53, 15))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(350, 70, 53, 15))
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 150, 53, 15))
        self.pushButton_f089 = QPushButton(self.tab_2)
        self.pushButton_f089.setObjectName(u"pushButton_f089")
        self.pushButton_f089.setGeometry(QRect(100, 130, 251, 41))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(350, 190, 53, 15))
        self.pushButton_f013 = QPushButton(self.tab_2)
        self.pushButton_f013.setObjectName(u"pushButton_f013")
        self.pushButton_f013.setGeometry(QRect(100, 170, 251, 41))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(350, 270, 53, 15))
        self.pushButton_f18b = QPushButton(self.tab_2)
        self.pushButton_f18b.setObjectName(u"pushButton_f18b")
        self.pushButton_f18b.setGeometry(QRect(140, 250, 211, 41))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 230, 53, 15))
        self.pushButton_f18a = QPushButton(self.tab_2)
        self.pushButton_f18a.setObjectName(u"pushButton_f18a")
        self.pushButton_f18a.setGeometry(QRect(100, 210, 251, 41))
        self.pushButton_f18c = QPushButton(self.tab_2)
        self.pushButton_f18c.setObjectName(u"pushButton_f18c")
        self.pushButton_f18c.setGeometry(QRect(130, 290, 221, 41))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(350, 310, 53, 15))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(350, 350, 53, 15))
        self.pushButton_f186 = QPushButton(self.tab_2)
        self.pushButton_f186.setObjectName(u"pushButton_f186")
        self.pushButton_f186.setGeometry(QRect(100, 330, 251, 41))
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(410, 60, 53, 15))
        self.pushButton_f0fe = QPushButton(self.tab_2)
        self.pushButton_f0fe.setObjectName(u"pushButton_f0fe")
        self.pushButton_f0fe.setGeometry(QRect(440, 50, 251, 41))
        self.pushButton_f190 = QPushButton(self.tab_2)
        self.pushButton_f190.setObjectName(u"pushButton_f190")
        self.pushButton_f190.setGeometry(QRect(440, 10, 251, 41))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(410, 30, 53, 15))
        self.lineEdit_f190 = QLineEdit(self.tab_2)
        self.lineEdit_f190.setObjectName(u"lineEdit_f190")
        self.lineEdit_f190.setGeometry(QRect(820, 20, 191, 31))
        self.lineEdit_f0fe = QLineEdit(self.tab_2)
        self.lineEdit_f0fe.setObjectName(u"lineEdit_f0fe")
        self.lineEdit_f0fe.setGeometry(QRect(820, 70, 191, 31))
        self.pushButton_f190_read = QPushButton(self.tab_2)
        self.pushButton_f190_read.setObjectName(u"pushButton_f190_read")
        self.pushButton_f190_read.setGeometry(QRect(700, 20, 61, 31))
        self.pushButton_f190_write = QPushButton(self.tab_2)
        self.pushButton_f190_write.setObjectName(u"pushButton_f190_write")
        self.pushButton_f190_write.setGeometry(QRect(760, 20, 61, 31))
        self.pushButton_f0fe_read = QPushButton(self.tab_2)
        self.pushButton_f0fe_read.setObjectName(u"pushButton_f0fe_read")
        self.pushButton_f0fe_read.setGeometry(QRect(700, 70, 61, 31))
        self.pushButton_f0fe_write = QPushButton(self.tab_2)
        self.pushButton_f0fe_write.setObjectName(u"pushButton_f0fe_write")
        self.pushButton_f0fe_write.setGeometry(QRect(760, 70, 61, 31))
        self.pushButton_f083 = QPushButton(self.tab_2)
        self.pushButton_f083.setObjectName(u"pushButton_f083")
        self.pushButton_f083.setGeometry(QRect(440, 170, 251, 41))
        self.pushButton_f086 = QPushButton(self.tab_2)
        self.pushButton_f086.setObjectName(u"pushButton_f086")
        self.pushButton_f086.setGeometry(QRect(440, 250, 251, 41))
        self.label_117 = QLabel(self.tab_2)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(410, 180, 53, 15))
        self.pushButton_f084 = QPushButton(self.tab_2)
        self.pushButton_f084.setObjectName(u"pushButton_f084")
        self.pushButton_f084.setGeometry(QRect(440, 210, 251, 41))
        self.label_118 = QLabel(self.tab_2)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(410, 230, 53, 15))
        self.label_119 = QLabel(self.tab_2)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(410, 270, 53, 15))
        self.pushButton_f087 = QPushButton(self.tab_2)
        self.pushButton_f087.setObjectName(u"pushButton_f087")
        self.pushButton_f087.setGeometry(QRect(440, 290, 251, 41))
        self.label_124 = QLabel(self.tab_2)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setGeometry(QRect(410, 310, 53, 15))
        self.pushButton_f08b = QPushButton(self.tab_2)
        self.pushButton_f08b.setObjectName(u"pushButton_f08b")
        self.pushButton_f08b.setGeometry(QRect(440, 330, 251, 41))
        self.label_125 = QLabel(self.tab_2)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(410, 350, 53, 15))
        self.label_126 = QLabel(self.tab_2)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setGeometry(QRect(410, 140, 53, 15))
        self.pushButton_f091 = QPushButton(self.tab_2)
        self.pushButton_f091.setObjectName(u"pushButton_f091")
        self.pushButton_f091.setGeometry(QRect(440, 130, 251, 41))
        self.label_127 = QLabel(self.tab_2)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setGeometry(QRect(410, 100, 53, 15))
        self.pushButton_f161 = QPushButton(self.tab_2)
        self.pushButton_f161.setObjectName(u"pushButton_f161")
        self.pushButton_f161.setGeometry(QRect(440, 90, 251, 41))
        self.label_128 = QLabel(self.tab_2)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setGeometry(QRect(350, 390, 53, 15))
        self.pushButton_f160 = QPushButton(self.tab_2)
        self.pushButton_f160.setObjectName(u"pushButton_f160")
        self.pushButton_f160.setGeometry(QRect(100, 370, 251, 41))
        self.pushButton_f180 = QPushButton(self.tab_2)
        self.pushButton_f180.setObjectName(u"pushButton_f180")
        self.pushButton_f180.setGeometry(QRect(100, 10, 251, 41))
        self.label_129 = QLabel(self.tab_2)
        self.label_129.setObjectName(u"label_129")
        self.label_129.setGeometry(QRect(350, 30, 53, 15))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_5703 = QPushButton(self.tab_3)
        self.pushButton_5703.setObjectName(u"pushButton_5703")
        self.pushButton_5703.setGeometry(QRect(71, 2, 79, 31))
        self.pushButton_5708 = QPushButton(self.tab_3)
        self.pushButton_5708.setObjectName(u"pushButton_5708")
        self.pushButton_5708.setGeometry(QRect(71, 32, 79, 31))
        self.pushButton_570e = QPushButton(self.tab_3)
        self.pushButton_570e.setObjectName(u"pushButton_570e")
        self.pushButton_570e.setGeometry(QRect(71, 62, 79, 31))
        self.pushButton_5717 = QPushButton(self.tab_3)
        self.pushButton_5717.setObjectName(u"pushButton_5717")
        self.pushButton_5717.setGeometry(QRect(71, 92, 79, 31))
        self.pushButton_5721 = QPushButton(self.tab_3)
        self.pushButton_5721.setObjectName(u"pushButton_5721")
        self.pushButton_5721.setGeometry(QRect(71, 122, 79, 31))
        self.pushButton_5722 = QPushButton(self.tab_3)
        self.pushButton_5722.setObjectName(u"pushButton_5722")
        self.pushButton_5722.setGeometry(QRect(71, 152, 79, 31))
        self.pushButton_5723 = QPushButton(self.tab_3)
        self.pushButton_5723.setObjectName(u"pushButton_5723")
        self.pushButton_5723.setGeometry(QRect(71, 182, 79, 31))
        self.pushButton_5724 = QPushButton(self.tab_3)
        self.pushButton_5724.setObjectName(u"pushButton_5724")
        self.pushButton_5724.setGeometry(QRect(71, 212, 79, 31))
        self.pushButton_5727 = QPushButton(self.tab_3)
        self.pushButton_5727.setObjectName(u"pushButton_5727")
        self.pushButton_5727.setGeometry(QRect(71, 242, 79, 31))
        self.pushButton_5728 = QPushButton(self.tab_3)
        self.pushButton_5728.setObjectName(u"pushButton_5728")
        self.pushButton_5728.setGeometry(QRect(71, 272, 79, 31))
        self.label_60 = QLabel(self.tab_3)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(161, 10, 24, 16))
        self.label_61 = QLabel(self.tab_3)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(161, 40, 120, 16))
        self.label_62 = QLabel(self.tab_3)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(161, 70, 120, 16))
        self.label_63 = QLabel(self.tab_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(161, 100, 120, 16))
        self.label_64 = QLabel(self.tab_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(161, 130, 120, 16))
        self.label_65 = QLabel(self.tab_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(161, 160, 120, 16))
        self.label_77 = QLabel(self.tab_3)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(161, 190, 120, 16))
        self.label_78 = QLabel(self.tab_3)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(161, 220, 120, 16))
        self.label_79 = QLabel(self.tab_3)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(161, 250, 120, 16))
        self.label_80 = QLabel(self.tab_3)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(161, 280, 120, 16))
        self.label_81 = QLabel(self.tab_3)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(450, 40, 120, 16))
        self.pushButton_d008 = QPushButton(self.tab_3)
        self.pushButton_d008.setObjectName(u"pushButton_d008")
        self.pushButton_d008.setGeometry(QRect(70, 362, 79, 31))
        self.pushButton_572f = QPushButton(self.tab_3)
        self.pushButton_572f.setObjectName(u"pushButton_572f")
        self.pushButton_572f.setGeometry(QRect(360, 92, 79, 31))
        self.pushButton_572a = QPushButton(self.tab_3)
        self.pushButton_572a.setObjectName(u"pushButton_572a")
        self.pushButton_572a.setGeometry(QRect(70, 332, 79, 31))
        self.label_82 = QLabel(self.tab_3)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(450, 10, 120, 16))
        self.pushButton_572e = QPushButton(self.tab_3)
        self.pushButton_572e.setObjectName(u"pushButton_572e")
        self.pushButton_572e.setGeometry(QRect(360, 62, 79, 31))
        self.pushButton_5739 = QPushButton(self.tab_3)
        self.pushButton_5739.setObjectName(u"pushButton_5739")
        self.pushButton_5739.setGeometry(QRect(70, 392, 79, 31))
        self.pushButton_572c = QPushButton(self.tab_3)
        self.pushButton_572c.setObjectName(u"pushButton_572c")
        self.pushButton_572c.setGeometry(QRect(360, 2, 79, 31))
        self.label_83 = QLabel(self.tab_3)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(160, 370, 120, 16))
        self.label_84 = QLabel(self.tab_3)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(450, 130, 120, 16))
        self.pushButton_5729 = QPushButton(self.tab_3)
        self.pushButton_5729.setObjectName(u"pushButton_5729")
        self.pushButton_5729.setGeometry(QRect(70, 302, 79, 31))
        self.pushButton_5730 = QPushButton(self.tab_3)
        self.pushButton_5730.setObjectName(u"pushButton_5730")
        self.pushButton_5730.setGeometry(QRect(360, 122, 79, 31))
        self.label_85 = QLabel(self.tab_3)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(450, 100, 120, 16))
        self.label_86 = QLabel(self.tab_3)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(160, 340, 120, 16))
        self.label_87 = QLabel(self.tab_3)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(160, 400, 120, 16))
        self.label_88 = QLabel(self.tab_3)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(160, 310, 111, 16))
        self.label_89 = QLabel(self.tab_3)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(450, 70, 120, 16))
        self.pushButton_572d = QPushButton(self.tab_3)
        self.pushButton_572d.setObjectName(u"pushButton_572d")
        self.pushButton_572d.setGeometry(QRect(360, 32, 79, 31))
        self.pushButton_572b = QPushButton(self.tab_3)
        self.pushButton_572b.setObjectName(u"pushButton_572b")
        self.pushButton_572b.setGeometry(QRect(70, 422, 79, 31))
        self.label_90 = QLabel(self.tab_3)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(160, 430, 120, 16))
        self.pushButton_573d = QPushButton(self.tab_3)
        self.pushButton_573d.setObjectName(u"pushButton_573d")
        self.pushButton_573d.setGeometry(QRect(360, 272, 79, 31))
        self.pushButton_573f = QPushButton(self.tab_3)
        self.pushButton_573f.setObjectName(u"pushButton_573f")
        self.pushButton_573f.setGeometry(QRect(360, 302, 79, 31))
        self.label_91 = QLabel(self.tab_3)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(450, 190, 141, 16))
        self.pushButton_573a = QPushButton(self.tab_3)
        self.pushButton_573a.setObjectName(u"pushButton_573a")
        self.pushButton_573a.setGeometry(QRect(360, 182, 79, 31))
        self.label_92 = QLabel(self.tab_3)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(450, 160, 121, 16))
        self.label_93 = QLabel(self.tab_3)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(450, 400, 120, 16))
        self.pushButton_5743 = QPushButton(self.tab_3)
        self.pushButton_5743.setObjectName(u"pushButton_5743")
        self.pushButton_5743.setGeometry(QRect(630, 12, 79, 31))
        self.label_94 = QLabel(self.tab_3)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(450, 310, 120, 16))
        self.label_95 = QLabel(self.tab_3)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(450, 340, 120, 16))
        self.pushButton_5741 = QPushButton(self.tab_3)
        self.pushButton_5741.setObjectName(u"pushButton_5741")
        self.pushButton_5741.setGeometry(QRect(360, 362, 79, 31))
        self.label_96 = QLabel(self.tab_3)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(450, 280, 120, 16))
        self.pushButton_5742 = QPushButton(self.tab_3)
        self.pushButton_5742.setObjectName(u"pushButton_5742")
        self.pushButton_5742.setGeometry(QRect(360, 392, 79, 31))
        self.label_97 = QLabel(self.tab_3)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(720, 20, 120, 16))
        self.label_98 = QLabel(self.tab_3)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(450, 370, 120, 16))
        self.label_99 = QLabel(self.tab_3)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(450, 250, 120, 16))
        self.pushButton_5731 = QPushButton(self.tab_3)
        self.pushButton_5731.setObjectName(u"pushButton_5731")
        self.pushButton_5731.setGeometry(QRect(360, 152, 79, 31))
        self.pushButton_573b = QPushButton(self.tab_3)
        self.pushButton_573b.setObjectName(u"pushButton_573b")
        self.pushButton_573b.setGeometry(QRect(360, 212, 79, 31))
        self.pushButton_5740 = QPushButton(self.tab_3)
        self.pushButton_5740.setObjectName(u"pushButton_5740")
        self.pushButton_5740.setGeometry(QRect(360, 332, 79, 31))
        self.pushButton_573c = QPushButton(self.tab_3)
        self.pushButton_573c.setObjectName(u"pushButton_573c")
        self.pushButton_573c.setGeometry(QRect(360, 242, 79, 31))
        self.label_100 = QLabel(self.tab_3)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(450, 220, 120, 16))
        self.pushButton_574f = QPushButton(self.tab_3)
        self.pushButton_574f.setObjectName(u"pushButton_574f")
        self.pushButton_574f.setGeometry(QRect(630, 162, 79, 31))
        self.pushButton_5750 = QPushButton(self.tab_3)
        self.pushButton_5750.setObjectName(u"pushButton_5750")
        self.pushButton_5750.setGeometry(QRect(630, 192, 79, 31))
        self.label_101 = QLabel(self.tab_3)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(720, 80, 120, 16))
        self.pushButton_5745 = QPushButton(self.tab_3)
        self.pushButton_5745.setObjectName(u"pushButton_5745")
        self.pushButton_5745.setGeometry(QRect(630, 72, 79, 31))
        self.label_102 = QLabel(self.tab_3)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(720, 50, 101, 16))
        self.label_103 = QLabel(self.tab_3)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(720, 290, 120, 16))
        self.pushButton_5784 = QPushButton(self.tab_3)
        self.pushButton_5784.setObjectName(u"pushButton_5784")
        self.pushButton_5784.setGeometry(QRect(630, 312, 79, 31))
        self.label_104 = QLabel(self.tab_3)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(720, 200, 120, 16))
        self.label_105 = QLabel(self.tab_3)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(720, 230, 120, 16))
        self.pushButton_5752 = QPushButton(self.tab_3)
        self.pushButton_5752.setObjectName(u"pushButton_5752")
        self.pushButton_5752.setGeometry(QRect(630, 252, 79, 31))
        self.label_106 = QLabel(self.tab_3)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(720, 170, 120, 16))
        self.pushButton_5753 = QPushButton(self.tab_3)
        self.pushButton_5753.setObjectName(u"pushButton_5753")
        self.pushButton_5753.setGeometry(QRect(630, 282, 79, 31))
        self.label_107 = QLabel(self.tab_3)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(720, 320, 120, 16))
        self.label_108 = QLabel(self.tab_3)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(720, 260, 120, 16))
        self.label_109 = QLabel(self.tab_3)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(720, 140, 120, 16))
        self.pushButton_5744 = QPushButton(self.tab_3)
        self.pushButton_5744.setObjectName(u"pushButton_5744")
        self.pushButton_5744.setGeometry(QRect(630, 42, 79, 31))
        self.pushButton_574d = QPushButton(self.tab_3)
        self.pushButton_574d.setObjectName(u"pushButton_574d")
        self.pushButton_574d.setGeometry(QRect(630, 102, 79, 31))
        self.pushButton_5751 = QPushButton(self.tab_3)
        self.pushButton_5751.setObjectName(u"pushButton_5751")
        self.pushButton_5751.setGeometry(QRect(630, 222, 79, 31))
        self.pushButton_574e = QPushButton(self.tab_3)
        self.pushButton_574e.setObjectName(u"pushButton_574e")
        self.pushButton_574e.setGeometry(QRect(630, 132, 79, 31))
        self.label_110 = QLabel(self.tab_3)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(720, 110, 120, 16))
        self.lineEdit_d008 = QLineEdit(self.tab_3)
        self.lineEdit_d008.setObjectName(u"lineEdit_d008")
        self.lineEdit_d008.setGeometry(QRect(220, 360, 113, 31))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_check_all_dtc = QPushButton(self.tab_4)
        self.pushButton_check_all_dtc.setObjectName(u"pushButton_check_all_dtc")
        self.pushButton_check_all_dtc.setGeometry(QRect(80, 80, 91, 31))
        self.pushButton_send_14 = QPushButton(self.tab_4)
        self.pushButton_send_14.setObjectName(u"pushButton_send_14")
        self.pushButton_send_14.setGeometry(QRect(190, 80, 91, 31))
        self.label_74 = QLabel(self.tab_4)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(90, 60, 111, 21))
        self.comboBox_single_dtc = QComboBox(self.tab_4)
        self.comboBox_single_dtc.setObjectName(u"comboBox_single_dtc")
        self.comboBox_single_dtc.setGeometry(QRect(80, 170, 431, 41))
        self.label_75 = QLabel(self.tab_4)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(90, 150, 121, 16))
        self.lineEdit_single_dtc = QLineEdit(self.tab_4)
        self.lineEdit_single_dtc.setObjectName(u"lineEdit_single_dtc")
        self.lineEdit_single_dtc.setGeometry(QRect(80, 250, 131, 31))
        self.pushButton_check_single_dtc = QPushButton(self.tab_4)
        self.pushButton_check_single_dtc.setObjectName(u"pushButton_check_single_dtc")
        self.pushButton_check_single_dtc.setGeometry(QRect(220, 250, 79, 31))
        self.label_76 = QLabel(self.tab_4)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(90, 230, 161, 16))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.pushButton_1060 = QPushButton(self.tab_6)
        self.pushButton_1060.setObjectName(u"pushButton_1060")
        self.pushButton_1060.setGeometry(QRect(30, 0, 131, 31))
        self.layoutWidget = QWidget(self.tab_6)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(390, 240, 242, 182))
        self.formLayout_2 = QFormLayout(self.layoutWidget)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_fd1c = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd1c.setObjectName(u"pushButton_eol_fd1c")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_fd1c)

        self.label_40 = QLabel(self.layoutWidget)
        self.label_40.setObjectName(u"label_40")

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.label_40)

        self.pushButton_eol_fd0b = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd0b.setObjectName(u"pushButton_eol_fd0b")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_fd0b)

        self.label_41 = QLabel(self.layoutWidget)
        self.label_41.setObjectName(u"label_41")

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.label_41)

        self.pushButton_eol_fd51 = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd51.setObjectName(u"pushButton_eol_fd51")

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_fd51)

        self.label_42 = QLabel(self.layoutWidget)
        self.label_42.setObjectName(u"label_42")

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.label_42)

        self.pushButton_eol_fd53 = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd53.setObjectName(u"pushButton_eol_fd53")

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_fd53)

        self.label_43 = QLabel(self.layoutWidget)
        self.label_43.setObjectName(u"label_43")

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.label_43)

        self.pushButton_eol_fd61 = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd61.setObjectName(u"pushButton_eol_fd61")

        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_fd61)

        self.label_44 = QLabel(self.layoutWidget)
        self.label_44.setObjectName(u"label_44")

        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.label_44)

        self.pushButton_eol_fd65 = QPushButton(self.layoutWidget)
        self.pushButton_eol_fd65.setObjectName(u"pushButton_eol_fd65")

        self.formLayout_2.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_fd65)

        self.label_45 = QLabel(self.layoutWidget)
        self.label_45.setObjectName(u"label_45")

        self.formLayout_2.setWidget(5, QFormLayout.FieldRole, self.label_45)

        self.layoutWidget_2 = QWidget(self.tab_6)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(660, 240, 257, 185))
        self.formLayout_3 = QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_fda0 = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_fda0.setObjectName(u"pushButton_eol_fda0")

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_fda0)

        self.label_46 = QLabel(self.layoutWidget_2)
        self.label_46.setObjectName(u"label_46")

        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.label_46)

        self.pushButton_eol_fd14 = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_fd14.setObjectName(u"pushButton_eol_fd14")

        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_fd14)

        self.label_47 = QLabel(self.layoutWidget_2)
        self.label_47.setObjectName(u"label_47")

        self.formLayout_3.setWidget(1, QFormLayout.FieldRole, self.label_47)

        self.pushButton_eol_fd70 = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_fd70.setObjectName(u"pushButton_eol_fd70")

        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_fd70)

        self.label_48 = QLabel(self.layoutWidget_2)
        self.label_48.setObjectName(u"label_48")

        self.formLayout_3.setWidget(2, QFormLayout.FieldRole, self.label_48)

        self.pushButton_eol_fdb5 = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_fdb5.setObjectName(u"pushButton_eol_fdb5")

        self.formLayout_3.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_fdb5)

        self.label_49 = QLabel(self.layoutWidget_2)
        self.label_49.setObjectName(u"label_49")

        self.formLayout_3.setWidget(3, QFormLayout.FieldRole, self.label_49)

        self.pushButton_eol_f08b = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_f08b.setObjectName(u"pushButton_eol_f08b")

        self.formLayout_3.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_f08b)

        self.label_50 = QLabel(self.layoutWidget_2)
        self.label_50.setObjectName(u"label_50")

        self.formLayout_3.setWidget(4, QFormLayout.FieldRole, self.label_50)

        self.pushButton_eol_f083 = QPushButton(self.layoutWidget_2)
        self.pushButton_eol_f083.setObjectName(u"pushButton_eol_f083")

        self.formLayout_3.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_f083)

        self.label_51 = QLabel(self.layoutWidget_2)
        self.label_51.setObjectName(u"label_51")

        self.formLayout_3.setWidget(5, QFormLayout.FieldRole, self.label_51)

        self.layoutWidget_3 = QWidget(self.tab_6)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(660, 50, 297, 182))
        self.formLayout_4 = QFormLayout(self.layoutWidget_3)
        self.formLayout_4.setObjectName(u"formLayout_4")
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_fd40 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fd40.setObjectName(u"pushButton_eol_fd40")

        self.formLayout_4.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_fd40)

        self.label_52 = QLabel(self.layoutWidget_3)
        self.label_52.setObjectName(u"label_52")

        self.formLayout_4.setWidget(0, QFormLayout.FieldRole, self.label_52)

        self.pushButton_eol_fd30 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fd30.setObjectName(u"pushButton_eol_fd30")

        self.formLayout_4.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_fd30)

        self.label_53 = QLabel(self.layoutWidget_3)
        self.label_53.setObjectName(u"label_53")

        self.formLayout_4.setWidget(1, QFormLayout.FieldRole, self.label_53)

        self.pushButton_eol_fd13 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fd13.setObjectName(u"pushButton_eol_fd13")

        self.formLayout_4.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_fd13)

        self.label_54 = QLabel(self.layoutWidget_3)
        self.label_54.setObjectName(u"label_54")

        self.formLayout_4.setWidget(2, QFormLayout.FieldRole, self.label_54)

        self.pushButton_eol_fda4 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fda4.setObjectName(u"pushButton_eol_fda4")

        self.formLayout_4.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_fda4)

        self.label_55 = QLabel(self.layoutWidget_3)
        self.label_55.setObjectName(u"label_55")

        self.formLayout_4.setWidget(3, QFormLayout.FieldRole, self.label_55)

        self.pushButton_eol_fda2 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fda2.setObjectName(u"pushButton_eol_fda2")

        self.formLayout_4.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_fda2)

        self.label_56 = QLabel(self.layoutWidget_3)
        self.label_56.setObjectName(u"label_56")

        self.formLayout_4.setWidget(4, QFormLayout.FieldRole, self.label_56)

        self.pushButton_eol_fda1 = QPushButton(self.layoutWidget_3)
        self.pushButton_eol_fda1.setObjectName(u"pushButton_eol_fda1")

        self.formLayout_4.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_fda1)

        self.label_57 = QLabel(self.layoutWidget_3)
        self.label_57.setObjectName(u"label_57")

        self.formLayout_4.setWidget(5, QFormLayout.FieldRole, self.label_57)

        self.horizontalSlider = QSlider(self.tab_6)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(20, 240, 301, 22))
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.verticalSlider = QSlider(self.tab_6)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(310, 10, 22, 241))
        self.verticalSlider.setOrientation(Qt.Orientation.Vertical)
        self.label_58 = QLabel(self.tab_6)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(290, 160, 53, 15))
        self.layoutWidget1 = QWidget(self.tab_6)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(390, 50, 244, 182))
        self.formLayout = QFormLayout(self.layoutWidget1)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_fdf7 = QPushButton(self.layoutWidget1)
        self.pushButton_eol_fdf7.setObjectName(u"pushButton_eol_fdf7")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_fdf7)

        self.label_35 = QLabel(self.layoutWidget1)
        self.label_35.setObjectName(u"label_35")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.label_35)

        self.pushButton_eol_da21 = QPushButton(self.layoutWidget1)
        self.pushButton_eol_da21.setObjectName(u"pushButton_eol_da21")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_da21)

        self.label_34 = QLabel(self.layoutWidget1)
        self.label_34.setObjectName(u"label_34")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.label_34)

        self.pushButton_eol_fd89 = QPushButton(self.layoutWidget1)
        self.pushButton_eol_fd89.setObjectName(u"pushButton_eol_fd89")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_fd89)

        self.label_37 = QLabel(self.layoutWidget1)
        self.label_37.setObjectName(u"label_37")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.label_37)

        self.pushButton_eol_fd15 = QPushButton(self.layoutWidget1)
        self.pushButton_eol_fd15.setObjectName(u"pushButton_eol_fd15")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_fd15)

        self.label_36 = QLabel(self.layoutWidget1)
        self.label_36.setObjectName(u"label_36")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.label_36)

        self.pushButton_eol_f116 = QPushButton(self.layoutWidget1)
        self.pushButton_eol_f116.setObjectName(u"pushButton_eol_f116")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_f116)

        self.label_39 = QLabel(self.layoutWidget1)
        self.label_39.setObjectName(u"label_39")

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.label_39)

        self.pushButton_eol_fd0c = QPushButton(self.layoutWidget1)
        self.pushButton_eol_fd0c.setObjectName(u"pushButton_eol_fd0c")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_fd0c)

        self.label_38 = QLabel(self.layoutWidget1)
        self.label_38.setObjectName(u"label_38")

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.label_38)

        self.widget = QWidget(self.tab_6)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(30, 250, 187, 213))
        self.formLayout_5 = QFormLayout(self.widget)
        self.formLayout_5.setObjectName(u"formLayout_5")
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_f1ae = QPushButton(self.widget)
        self.pushButton_eol_f1ae.setObjectName(u"pushButton_eol_f1ae")

        self.formLayout_5.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_f1ae)

        self.label_28 = QLabel(self.widget)
        self.label_28.setObjectName(u"label_28")

        self.formLayout_5.setWidget(0, QFormLayout.FieldRole, self.label_28)

        self.pushButton_eol_da10 = QPushButton(self.widget)
        self.pushButton_eol_da10.setObjectName(u"pushButton_eol_da10")

        self.formLayout_5.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_da10)

        self.label_29 = QLabel(self.widget)
        self.label_29.setObjectName(u"label_29")

        self.formLayout_5.setWidget(1, QFormLayout.FieldRole, self.label_29)

        self.pushButton_eol_f195 = QPushButton(self.widget)
        self.pushButton_eol_f195.setObjectName(u"pushButton_eol_f195")

        self.formLayout_5.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_f195)

        self.label_23 = QLabel(self.widget)
        self.label_23.setObjectName(u"label_23")

        self.formLayout_5.setWidget(2, QFormLayout.FieldRole, self.label_23)

        self.pushButton_eol_fd98 = QPushButton(self.widget)
        self.pushButton_eol_fd98.setObjectName(u"pushButton_eol_fd98")

        self.formLayout_5.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_fd98)

        self.label_33 = QLabel(self.widget)
        self.label_33.setObjectName(u"label_33")

        self.formLayout_5.setWidget(3, QFormLayout.FieldRole, self.label_33)

        self.pushButton_eol_fd00 = QPushButton(self.widget)
        self.pushButton_eol_fd00.setObjectName(u"pushButton_eol_fd00")

        self.formLayout_5.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_fd00)

        self.label_30 = QLabel(self.widget)
        self.label_30.setObjectName(u"label_30")

        self.formLayout_5.setWidget(4, QFormLayout.FieldRole, self.label_30)

        self.pushButton_eol_f193 = QPushButton(self.widget)
        self.pushButton_eol_f193.setObjectName(u"pushButton_eol_f193")

        self.formLayout_5.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_f193)

        self.label_31 = QLabel(self.widget)
        self.label_31.setObjectName(u"label_31")

        self.formLayout_5.setWidget(5, QFormLayout.FieldRole, self.label_31)

        self.pushButton_eol_fdf6 = QPushButton(self.widget)
        self.pushButton_eol_fdf6.setObjectName(u"pushButton_eol_fdf6")

        self.formLayout_5.setWidget(6, QFormLayout.LabelRole, self.pushButton_eol_fdf6)

        self.label_32 = QLabel(self.widget)
        self.label_32.setObjectName(u"label_32")

        self.formLayout_5.setWidget(6, QFormLayout.FieldRole, self.label_32)

        self.widget1 = QWidget(self.tab_6)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(30, 30, 250, 213))
        self.formLayout_6 = QFormLayout(self.widget1)
        self.formLayout_6.setObjectName(u"formLayout_6")
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.pushButton_eol_f187 = QPushButton(self.widget1)
        self.pushButton_eol_f187.setObjectName(u"pushButton_eol_f187")

        self.formLayout_6.setWidget(0, QFormLayout.LabelRole, self.pushButton_eol_f187)

        self.label_18 = QLabel(self.widget1)
        self.label_18.setObjectName(u"label_18")

        self.formLayout_6.setWidget(0, QFormLayout.FieldRole, self.label_18)

        self.pushButton_eol_f189 = QPushButton(self.widget1)
        self.pushButton_eol_f189.setObjectName(u"pushButton_eol_f189")

        self.formLayout_6.setWidget(1, QFormLayout.LabelRole, self.pushButton_eol_f189)

        self.label_21 = QLabel(self.widget1)
        self.label_21.setObjectName(u"label_21")

        self.formLayout_6.setWidget(1, QFormLayout.FieldRole, self.label_21)

        self.pushButton_eol_f089 = QPushButton(self.widget1)
        self.pushButton_eol_f089.setObjectName(u"pushButton_eol_f089")

        self.formLayout_6.setWidget(2, QFormLayout.LabelRole, self.pushButton_eol_f089)

        self.label_22 = QLabel(self.widget1)
        self.label_22.setObjectName(u"label_22")

        self.formLayout_6.setWidget(2, QFormLayout.FieldRole, self.label_22)

        self.pushButton_eol_f013 = QPushButton(self.widget1)
        self.pushButton_eol_f013.setObjectName(u"pushButton_eol_f013")

        self.formLayout_6.setWidget(3, QFormLayout.LabelRole, self.pushButton_eol_f013)

        self.label_24 = QLabel(self.widget1)
        self.label_24.setObjectName(u"label_24")

        self.formLayout_6.setWidget(3, QFormLayout.FieldRole, self.label_24)

        self.pushButton_eol_f18a = QPushButton(self.widget1)
        self.pushButton_eol_f18a.setObjectName(u"pushButton_eol_f18a")

        self.formLayout_6.setWidget(4, QFormLayout.LabelRole, self.pushButton_eol_f18a)

        self.label_26 = QLabel(self.widget1)
        self.label_26.setObjectName(u"label_26")

        self.formLayout_6.setWidget(4, QFormLayout.FieldRole, self.label_26)

        self.pushButton_eol_f18b = QPushButton(self.widget1)
        self.pushButton_eol_f18b.setObjectName(u"pushButton_eol_f18b")

        self.formLayout_6.setWidget(5, QFormLayout.LabelRole, self.pushButton_eol_f18b)

        self.label_25 = QLabel(self.widget1)
        self.label_25.setObjectName(u"label_25")

        self.formLayout_6.setWidget(5, QFormLayout.FieldRole, self.label_25)

        self.pushButton_eol_f18c = QPushButton(self.widget1)
        self.pushButton_eol_f18c.setObjectName(u"pushButton_eol_f18c")

        self.formLayout_6.setWidget(6, QFormLayout.LabelRole, self.pushButton_eol_f18c)

        self.label_27 = QLabel(self.widget1)
        self.label_27.setObjectName(u"label_27")

        self.formLayout_6.setWidget(6, QFormLayout.FieldRole, self.label_27)

        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.pushButton_571d_01 = QPushButton(self.tab_7)
        self.pushButton_571d_01.setObjectName(u"pushButton_571d_01")
        self.pushButton_571d_01.setGeometry(QRect(180, 40, 79, 23))
        self.pushButton_571d_02 = QPushButton(self.tab_7)
        self.pushButton_571d_02.setObjectName(u"pushButton_571d_02")
        self.pushButton_571d_02.setGeometry(QRect(180, 80, 79, 23))
        self.pushButton_571e_01 = QPushButton(self.tab_7)
        self.pushButton_571e_01.setObjectName(u"pushButton_571e_01")
        self.pushButton_571e_01.setGeometry(QRect(180, 175, 79, 23))
        self.pushButton_571e_00 = QPushButton(self.tab_7)
        self.pushButton_571e_00.setObjectName(u"pushButton_571e_00")
        self.pushButton_571e_00.setGeometry(QRect(180, 135, 79, 23))
        self.pushButton_571e_03 = QPushButton(self.tab_7)
        self.pushButton_571e_03.setObjectName(u"pushButton_571e_03")
        self.pushButton_571e_03.setGeometry(QRect(180, 255, 79, 23))
        self.pushButton_571e_02 = QPushButton(self.tab_7)
        self.pushButton_571e_02.setObjectName(u"pushButton_571e_02")
        self.pushButton_571e_02.setGeometry(QRect(180, 215, 79, 23))
        self.label_111 = QLabel(self.tab_7)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(260, 210, 171, 31))
        self.label_112 = QLabel(self.tab_7)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(260, 245, 221, 41))
        self.pushButton_571f_02 = QPushButton(self.tab_7)
        self.pushButton_571f_02.setObjectName(u"pushButton_571f_02")
        self.pushButton_571f_02.setGeometry(QRect(180, 350, 79, 23))
        self.pushButton_571f_01 = QPushButton(self.tab_7)
        self.pushButton_571f_01.setObjectName(u"pushButton_571f_01")
        self.pushButton_571f_01.setGeometry(QRect(180, 310, 79, 23))
        self.label_113 = QLabel(self.tab_7)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(120, 60, 91, 31))
        self.label_114 = QLabel(self.tab_7)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(130, 195, 91, 31))
        self.label_115 = QLabel(self.tab_7)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(120, 330, 53, 31))
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.pushButton_read_f011 = QPushButton(self.tab_8)
        self.pushButton_read_f011.setObjectName(u"pushButton_read_f011")
        self.pushButton_read_f011.setGeometry(QRect(410, 200, 111, 51))
        self.label_116 = QLabel(self.tab_8)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(410, 260, 121, 20))
        self.lineEdit_byte = QLineEdit(self.tab_8)
        self.lineEdit_byte.setObjectName(u"lineEdit_byte")
        self.lineEdit_byte.setGeometry(QRect(520, 250, 31, 31))
        self.pushButton_f011_analyze = QPushButton(self.tab_8)
        self.pushButton_f011_analyze.setObjectName(u"pushButton_f011_analyze")
        self.pushButton_f011_analyze.setGeometry(QRect(560, 240, 71, 41))
        self.tabWidget.addTab(self.tab_8, "")
        self.textBrowser = QTextBrowser(Dialog)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 560, 1021, 241))
        self.pushButton_clear_log = QPushButton(Dialog)
        self.pushButton_clear_log.setObjectName(u"pushButton_clear_log")
        self.pushButton_clear_log.setGeometry(QRect(950, 520, 75, 31))
        self.pushButton_save_log = QPushButton(Dialog)
        self.pushButton_save_log.setObjectName(u"pushButton_save_log")
        self.pushButton_save_log.setGeometry(QRect(870, 520, 75, 31))
        self.textEdit_free_input = QTextEdit(Dialog)
        self.textEdit_free_input.setObjectName(u"textEdit_free_input")
        self.textEdit_free_input.setGeometry(QRect(10, 500, 331, 31))
        self.pushButton_send = QPushButton(Dialog)
        self.pushButton_send.setObjectName(u"pushButton_send")
        self.pushButton_send.setGeometry(QRect(340, 510, 75, 41))
        self.comboBox = QComboBox(Dialog)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 530, 331, 23))
        self.radioButton_physical = QRadioButton(Dialog)
        self.radioButton_physical.setObjectName(u"radioButton_physical")
        self.radioButton_physical.setGeometry(QRect(420, 530, 98, 19))
        self.radioButton_functional = QRadioButton(Dialog)
        self.radioButton_functional.setObjectName(u"radioButton_functional")
        self.radioButton_functional.setGeometry(QRect(500, 530, 98, 19))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"Mannual", None))
        self.pushButton_undefined_3.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e493", None))
        self.pushButton_undefined_9.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e499", None))
        self.pushButton_undefined_2.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e492", None))
        self.pushButton_undefined_8.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e498", None))
        self.pushButton_undefined_4.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e494", None))
        self.pushButton_undefined_6.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e496", None))
        self.pushButton_undefined_1.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e491", None))
        self.pushButton_undefined_10.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4910", None))
        self.pushButton_undefined_7.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e497", None))
        self.pushButton_undefined_5.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e495", None))
        self.pushButton_undefined_11.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4911", None))
        self.pushButton_undefined_12.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4912", None))
        self.pushButton_undefined_13.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4913", None))
        self.pushButton_undefined_14.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4914", None))
        self.pushButton_undefined_15.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4915", None))
        self.pushButton_undefined_16.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4916", None))
        self.pushButton_undefined_17.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4917", None))
        self.pushButton_undefined_18.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4918", None))
        self.pushButton_undefined_19.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4919", None))
        self.pushButton_undefined_20.setText(QCoreApplication.translate("Dialog", u"\u672a\u5b9a\u4e4920", None))
        self.label_120.setText(QCoreApplication.translate("Dialog", u"button_name_1", None))
        self.label_121.setText(QCoreApplication.translate("Dialog", u"button_name_10", None))
        self.label_122.setText(QCoreApplication.translate("Dialog", u"button_name_11", None))
        self.label_123.setText(QCoreApplication.translate("Dialog", u"button_name_20", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("Dialog", u"\u81ea\u5b9a\u4e49", None))
        self.pushButton_extendedDiagnosticSession.setText(QCoreApplication.translate("Dialog", u"extendedDiagnosticSession", None))
        self.pushButton_defaultSession.setText(QCoreApplication.translate("Dialog", u"defaultSession", None))
        self.pushButton_hardReset.setText(QCoreApplication.translate("Dialog", u"hardReset", None))
        self.pushButton_softReset.setText(QCoreApplication.translate("Dialog", u"softReset", None))
        self.pushButton_SecurityAccess.setText(QCoreApplication.translate("Dialog", u"SecurityAccess_0102", None))
        self.pushButton_13.setText(QCoreApplication.translate("Dialog", u"CommunicationControl", None))
        self.pushButton_ControlDTCSetting_Off.setText(QCoreApplication.translate("Dialog", u"Off", None))
        self.pushButton_ControlDTCSetting_On.setText(QCoreApplication.translate("Dialog", u"On", None))
        self.pushButton_ControlDTCSetting.setText(QCoreApplication.translate("Dialog", u"ControlDTCSetting", None))
        self.pushButton_TesterPresent.setText(QCoreApplication.translate("Dialog", u"TesterPresent", None))
        self.pushButton_ControlDTCSetting_On_2.setText(QCoreApplication.translate("Dialog", u"reportNumberOfDTCByStatusMask", None))
        self.pushButton_ReadDTCInformation.setText(QCoreApplication.translate("Dialog", u"ReadDTCInformation", None))
        self.pushButton_ControlDTCSetting_Off_2.setText(QCoreApplication.translate("Dialog", u"reportSupportedDTC", None))
        self.pushButton_stopRoutine.setText(QCoreApplication.translate("Dialog", u"stopRoutine", None))
        self.pushButton_RequestRoutineResults.setText(QCoreApplication.translate("Dialog", u"RequestRoutineResults", None))
        self.pushButton_StartRoutine.setText(QCoreApplication.translate("Dialog", u"StartRoutine", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"2701/02", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"3E", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"85", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"28", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"19", None))
        self.label_66.setText(QCoreApplication.translate("Dialog", u"Diagnostic\n"
"SessionControl", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"1001", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"1003", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"ECUReset", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"1101", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"1103", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"00-enableRxAndTx", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"03-disableRxAndTx", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"31-RoutineControl", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"2705/06", None))
        self.pushButton_SecurityAccess_0506.setText(QCoreApplication.translate("Dialog", u"SecurityAccess_0506", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"02.1.ApplicationServices", None))
        self.pushButton_f187.setText(QCoreApplication.translate("Dialog", u"vehicleManufacturerSparePart\n"
"NumberDataIdentifier", None))
        self.pushButton_f189.setText(QCoreApplication.translate("Dialog", u"vehicleManufacturerECU\n"
"SoftwareVersionNumberDataIdentifier", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"f189", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"f187", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"f089", None))
        self.pushButton_f089.setText(QCoreApplication.translate("Dialog", u"vehicleManufacturerECUHardware\n"
"VersionNumberDataIdentifier", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"f013", None))
        self.pushButton_f013.setText(QCoreApplication.translate("Dialog", u"vehicleManufacturer\n"
"LogisticSoftwarePartNumberDataIdentifier", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"f18b", None))
        self.pushButton_f18b.setText(QCoreApplication.translate("Dialog", u"ECU manufacturing date", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"f18a", None))
        self.pushButton_f18a.setText(QCoreApplication.translate("Dialog", u"systemSupplierIdentifierDataIdentifier", None))
        self.pushButton_f18c.setText(QCoreApplication.translate("Dialog", u"ECUSerialNumberDataIdentifier", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"f18c", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"f186", None))
        self.pushButton_f186.setText(QCoreApplication.translate("Dialog", u"ActiveDiagnosticSession", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"f0fe", None))
        self.pushButton_f0fe.setText(QCoreApplication.translate("Dialog", u"Vehicle Material Number", None))
        self.pushButton_f190.setText(QCoreApplication.translate("Dialog", u"VINDataIdentifier", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"f190", None))
        self.pushButton_f190_read.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.pushButton_f190_write.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.pushButton_f0fe_read.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.pushButton_f0fe_write.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.pushButton_f083.setText(QCoreApplication.translate("Dialog", u"CERT StoreStatus", None))
        self.pushButton_f086.setText(QCoreApplication.translate("Dialog", u"Read CERT SN", None))
        self.label_117.setText(QCoreApplication.translate("Dialog", u"f083", None))
        self.pushButton_f084.setText(QCoreApplication.translate("Dialog", u"CERT Effectived status", None))
        self.label_118.setText(QCoreApplication.translate("Dialog", u"f084", None))
        self.label_119.setText(QCoreApplication.translate("Dialog", u"f086", None))
        self.pushButton_f087.setText(QCoreApplication.translate("Dialog", u"Vehicle Material Number", None))
        self.label_124.setText(QCoreApplication.translate("Dialog", u"f087", None))
        self.pushButton_f08b.setText(QCoreApplication.translate("Dialog", u"Read CSR Store status", None))
        self.label_125.setText(QCoreApplication.translate("Dialog", u"f08b", None))
        self.label_126.setText(QCoreApplication.translate("Dialog", u"f091", None))
        self.pushButton_f091.setText(QCoreApplication.translate("Dialog", u"Mapping between DTC and DTC Number", None))
        self.label_127.setText(QCoreApplication.translate("Dialog", u"f161", None))
        self.pushButton_f161.setText(QCoreApplication.translate("Dialog", u"secure event log", None))
        self.label_128.setText(QCoreApplication.translate("Dialog", u"f160", None))
        self.pushButton_f160.setText(QCoreApplication.translate("Dialog", u"Signature Public Key Status", None))
        self.pushButton_f180.setText(QCoreApplication.translate("Dialog", u"BootSoftwareIdentificationDataIdentifier", None))
        self.label_129.setText(QCoreApplication.translate("Dialog", u"f180", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"03.1.System DID", None))
        self.pushButton_5703.setText(QCoreApplication.translate("Dialog", u"5703", None))
        self.pushButton_5708.setText(QCoreApplication.translate("Dialog", u"5708", None))
        self.pushButton_570e.setText(QCoreApplication.translate("Dialog", u"570E", None))
        self.pushButton_5717.setText(QCoreApplication.translate("Dialog", u"5717", None))
        self.pushButton_5721.setText(QCoreApplication.translate("Dialog", u"5721", None))
        self.pushButton_5722.setText(QCoreApplication.translate("Dialog", u"5722", None))
        self.pushButton_5723.setText(QCoreApplication.translate("Dialog", u"5723", None))
        self.pushButton_5724.setText(QCoreApplication.translate("Dialog", u"5724", None))
        self.pushButton_5727.setText(QCoreApplication.translate("Dialog", u"5727", None))
        self.pushButton_5728.setText(QCoreApplication.translate("Dialog", u"5728", None))
        self.label_60.setText(QCoreApplication.translate("Dialog", u"\u8f66\u901f", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"\u8f93\u5165\u72b6\u6001\uff08\u5f00\u5173\u4fe1\u53f7\uff09", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"\u5012\u6863\u72b6\u6001", None))
        self.label_63.setText(QCoreApplication.translate("Dialog", u"\u9ea6\u514b\u98ce\u6570\u91cf", None))
        self.label_64.setText(QCoreApplication.translate("Dialog", u"BiTECH\u4ea7\u7ebf\u751f\u4ea7\u65e5\u671f", None))
        self.label_65.setText(QCoreApplication.translate("Dialog", u"Android kernel\u7248\u672c", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"Android\u7248\u672c", None))
        self.label_78.setText(QCoreApplication.translate("Dialog", u"MCU\u8f6f\u4ef6\u7248\u672c", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"\u4ee5\u592a\u7aef\u53e3\u7684\u6700\u5c0fSQI", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"\u5f53\u524d\u7aef\u53e3\u4fe1\u53f7\u8d28\u91cf", None))
        self.label_81.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u786c\u4ef6\u7248\u672c", None))
        self.pushButton_d008.setText(QCoreApplication.translate("Dialog", u"D008", None))
        self.pushButton_572f.setText(QCoreApplication.translate("Dialog", u"572F", None))
        self.pushButton_572a.setText(QCoreApplication.translate("Dialog", u"572A", None))
        self.label_82.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u8f6f\u4ef6\u96f6\u4ef6\u53f7", None))
        self.pushButton_572e.setText(QCoreApplication.translate("Dialog", u"572E", None))
        self.pushButton_5739.setText(QCoreApplication.translate("Dialog", u"5739", None))
        self.pushButton_572c.setText(QCoreApplication.translate("Dialog", u"572C", None))
        self.label_83.setText(QCoreApplication.translate("Dialog", u"SC(PIN)\u7801", None))
        self.label_84.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u5e8f\u5217\u53f7", None))
        self.pushButton_5729.setText(QCoreApplication.translate("Dialog", u"5729", None))
        self.pushButton_5730.setText(QCoreApplication.translate("Dialog", u"5730", None))
        self.label_85.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u4f9b\u5e94\u5546\u4ee3\u7801", None))
        self.label_86.setText(QCoreApplication.translate("Dialog", u"\u6d4b\u8bd5\u6a21\u5f0f\u72b6\u6001", None))
        self.label_87.setText(QCoreApplication.translate("Dialog", u"ICC\u9632\u76d7\u72b6\u6001", None))
        self.label_88.setText(QCoreApplication.translate("Dialog", u"\u4e3b/\u4ece\u72b6\u6001", None))
        self.label_89.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u8f6f\u4ef6\u7248\u672c", None))
        self.pushButton_572d.setText(QCoreApplication.translate("Dialog", u"572D", None))
        self.pushButton_572b.setText(QCoreApplication.translate("Dialog", u"572B", None))
        self.label_90.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4f\u96f6\u4ef6\u53f7", None))
        self.pushButton_573d.setText(QCoreApplication.translate("Dialog", u"573D", None))
        self.pushButton_573f.setText(QCoreApplication.translate("Dialog", u"573F", None))
        self.label_91.setText(QCoreApplication.translate("Dialog", u"ICC \u5f53\u524d\u6a21\u5f0f(ADB/USB)", None))
        self.pushButton_573a.setText(QCoreApplication.translate("Dialog", u"573A", None))
        self.label_92.setText(QCoreApplication.translate("Dialog", u"\u4e2d\u63a7\u5c4fBOOT\u7248\u672c\u53f7", None))
        self.label_93.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u8f6f\u4ef6\u7248\u672c", None))
        self.pushButton_5743.setText(QCoreApplication.translate("Dialog", u"5743", None))
        self.label_94.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u96f6\u4ef6\u53f7", None))
        self.label_95.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u8f6f\u4ef6\u96f6\u4ef6\u53f7", None))
        self.pushButton_5741.setText(QCoreApplication.translate("Dialog", u"5741", None))
        self.label_96.setText(QCoreApplication.translate("Dialog", u"WIFI \u5bc6\u7801", None))
        self.pushButton_5742.setText(QCoreApplication.translate("Dialog", u"5742", None))
        self.label_97.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u4f9b\u5e94\u5546\u4ee3\u7801", None))
        self.label_98.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u786c\u4ef6\u7248\u672c", None))
        self.label_99.setText(QCoreApplication.translate("Dialog", u"SSID", None))
        self.pushButton_5731.setText(QCoreApplication.translate("Dialog", u"5731", None))
        self.pushButton_573b.setText(QCoreApplication.translate("Dialog", u"573B", None))
        self.pushButton_5740.setText(QCoreApplication.translate("Dialog", u"5740", None))
        self.pushButton_573c.setText(QCoreApplication.translate("Dialog", u"573C", None))
        self.label_100.setText(QCoreApplication.translate("Dialog", u"ICC \u5f53\u524d\u662f\u5426\u5b58\u5728\u6574\u8f66\u68c0\u6d4bapp", None))
        self.pushButton_574f.setText(QCoreApplication.translate("Dialog", u"574F", None))
        self.pushButton_5750.setText(QCoreApplication.translate("Dialog", u"5750", None))
        self.label_101.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4fBOOT\u7248\u672c", None))
        self.pushButton_5745.setText(QCoreApplication.translate("Dialog", u"5745", None))
        self.label_102.setText(QCoreApplication.translate("Dialog", u"\u4eea\u8868\u5c4f\u5e8f\u5217\u53f7", None))
        self.label_103.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4fBOOT\u7248\u672c", None))
        self.pushButton_5784.setText(QCoreApplication.translate("Dialog", u"5784", None))
        self.label_104.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u8f6f\u4ef6\u7248\u672c", None))
        self.label_105.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u4f9b\u5e94\u5546\u4ee3\u7801", None))
        self.pushButton_5752.setText(QCoreApplication.translate("Dialog", u"5752", None))
        self.label_106.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u786c\u4ef6\u7248\u672c", None))
        self.pushButton_5753.setText(QCoreApplication.translate("Dialog", u"5753", None))
        self.label_107.setText(QCoreApplication.translate("Dialog", u"\u5f53\u524d\u4fdd\u517b\u4fe1\u606f", None))
        self.label_108.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u5e8f\u5217\u53f7", None))
        self.label_109.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u8f6f\u4ef6\u96f6\u4ef6\u53f7", None))
        self.pushButton_5744.setText(QCoreApplication.translate("Dialog", u"5744", None))
        self.pushButton_574d.setText(QCoreApplication.translate("Dialog", u"574D", None))
        self.pushButton_5751.setText(QCoreApplication.translate("Dialog", u"5751", None))
        self.pushButton_574e.setText(QCoreApplication.translate("Dialog", u"574E", None))
        self.label_110.setText(QCoreApplication.translate("Dialog", u"\u5438\u9876\u5c4f\u96f6\u4ef6\u53f7", None))
        self.lineEdit_d008.setText(QCoreApplication.translate("Dialog", u"Byte*4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"03.2.ECU DID", None))
        self.pushButton_check_all_dtc.setText(QCoreApplication.translate("Dialog", u"CheckAllDTC", None))
        self.pushButton_send_14.setText(QCoreApplication.translate("Dialog", u"send 14", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"\u68c0\u67e5\u6240\u6709\u6545\u969c", None))
        self.label_75.setText(QCoreApplication.translate("Dialog", u"\u4e0b\u62c9\u67e5\u8be2\u5355\u4e2a\u6545\u969c", None))
        self.lineEdit_single_dtc.setText(QCoreApplication.translate("Dialog", u"\u4f8b\u5982\uff1aU118987", None))
        self.pushButton_check_single_dtc.setText(QCoreApplication.translate("Dialog", u"\u67e5\u8be2", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"\u8f93\u5165\u6545\u969c\u7801\u67e5\u8be2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"04.2.DTC list ", None))
        self.pushButton_1060.setText(QCoreApplication.translate("Dialog", u"\u53d1\u90011060\u5e76\u7ef4\u6301", None))
        self.pushButton_eol_fd1c.setText(QCoreApplication.translate("Dialog", u"FD1C", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"\u71c3\u6cb9\u91cf\u68c0\u6d4b", None))
        self.pushButton_eol_fd0b.setText(QCoreApplication.translate("Dialog", u"FD0B", None))
        self.label_41.setText(QCoreApplication.translate("Dialog", u"\u7535\u6e90\u4f9b\u7535\u68c0\u6d4b\uff08\u529f\u80fd\u5b89\u5168\uff09", None))
        self.pushButton_eol_fd51.setText(QCoreApplication.translate("Dialog", u"FD51", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"\u6253\u5f00/\u5173\u95edBT1\u548cBT2", None))
        self.pushButton_eol_fd53.setText(QCoreApplication.translate("Dialog", u"FD53", None))
        self.label_43.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6BT1\u548cBT2\u7684MAC\u5730\u5740", None))
        self.pushButton_eol_fd61.setText(QCoreApplication.translate("Dialog", u"FD61", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"\u6253\u5f00/\u5173\u95edWiFi", None))
        self.pushButton_eol_fd65.setText(QCoreApplication.translate("Dialog", u"FD65", None))
        self.label_45.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6WiFi\u6a21\u5757\u7684MAC\u5730\u5740", None))
        self.pushButton_eol_fda0.setText(QCoreApplication.translate("Dialog", u"FDA0", None))
        self.label_46.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6USB2.0\u63a5\u53e3\u7684\u4fe1\u606f\u53ca\u901f\u7387", None))
        self.pushButton_eol_fd14.setText(QCoreApplication.translate("Dialog", u"FD14", None))
        self.label_47.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6camera POC\u4f9b\u7535\u7684\u7535\u6d41\u503c", None))
        self.pushButton_eol_fd70.setText(QCoreApplication.translate("Dialog", u"FD70", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6\u82f9\u679c\u82af\u7247\u7684\u4fe1\u606f", None))
        self.pushButton_eol_fdb5.setText(QCoreApplication.translate("Dialog", u"FDB5", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6UFS\u7684\u5065\u5eb7\u62a5\u544a", None))
        self.pushButton_eol_f08b.setText(QCoreApplication.translate("Dialog", u"F08B", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"\u68c0\u67e5CSR\u5b58\u50a8\u72b6\u6001", None))
        self.pushButton_eol_f083.setText(QCoreApplication.translate("Dialog", u"F083", None))
        self.label_51.setText(QCoreApplication.translate("Dialog", u"\u68c0\u67e5\u6839\u8bc1\u4e66\u72b6\u6001", None))
        self.pushButton_eol_fd40.setText(QCoreApplication.translate("Dialog", u"FD40", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6FM\u5f53\u524d\u5bf9\u5e94\u7684\u9891\u9053", None))
        self.pushButton_eol_fd30.setText(QCoreApplication.translate("Dialog", u"FD30", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"\u8bbe\u7f6e\u97f3\u91cf", None))
        self.pushButton_eol_fd13.setText(QCoreApplication.translate("Dialog", u"FD13", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d6A2B1/A2B2/A2B3\u7684\u5916\u8bbe\u8fde\u63a5\u72b6\u6001", None))
        self.pushButton_eol_fda4.setText(QCoreApplication.translate("Dialog", u"FDA4", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"\u4f7f\u80fd2\u8defUSB3.0\u63a5\u53e3\u5145\u7535", None))
        self.pushButton_eol_fda2.setText(QCoreApplication.translate("Dialog", u"FDA2", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d62\u8defUSB3.0\u63a5\u53e3\u5145\u7535\u529f\u7387\u72b6\u6001", None))
        self.pushButton_eol_fda1.setText(QCoreApplication.translate("Dialog", u"FDA1", None))
        self.label_57.setText(QCoreApplication.translate("Dialog", u"\u8bfb\u53d62\u8defUSB3.0\u63a5\u53e3\u7684\u4fe1\u606f\u53ca\u901f\u7387", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"pass", None))
        self.pushButton_eol_fdf7.setText(QCoreApplication.translate("Dialog", u"FDF7", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"\u603b\u6210\u5e8f\u5217\u53f7", None))
        self.pushButton_eol_da21.setText(QCoreApplication.translate("Dialog", u"DA21", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"\u5173\u95ed\u8c03\u8bd5\u53e3", None))
        self.pushButton_eol_fd89.setText(QCoreApplication.translate("Dialog", u"FDB9", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"Efuse\u5b8c\u6574\u6027\u68c0\u67e5", None))
        self.pushButton_eol_fd15.setText(QCoreApplication.translate("Dialog", u"FD15", None))
        self.label_36.setText(QCoreApplication.translate("Dialog", u"\u663e\u793a\u5c4f\u4f7f\u80fd\u4fe1\u53f7\u68c0\u67e5", None))
        self.pushButton_eol_f116.setText(QCoreApplication.translate("Dialog", u"FD16", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"\u663e\u793a\u5c4f\u7684ERR\u4fe1\u53f7\u91c7\u96c6\u53e3\u68c0\u67e5", None))
        self.pushButton_eol_fd0c.setText(QCoreApplication.translate("Dialog", u"FD0C", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"\u603b\u6210\u53f7", None))
        self.pushButton_eol_f1ae.setText(QCoreApplication.translate("Dialog", u"F1AE", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"\u8f6f\u4ef6\u96f6\u4ef6\u53f7", None))
        self.pushButton_eol_da10.setText(QCoreApplication.translate("Dialog", u"DA10", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"MCU\u8f6f\u4ef6\u7248\u672c\u53f7", None))
        self.pushButton_eol_f195.setText(QCoreApplication.translate("Dialog", u"F195", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"SOC\u8f6f\u4ef6\u7248\u672c\u53f7", None))
        self.pushButton_eol_fd98.setText(QCoreApplication.translate("Dialog", u"FD98", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"DP IN \u56fa\u4ef6\u7248\u672c\u53f7", None))
        self.pushButton_eol_fd00.setText(QCoreApplication.translate("Dialog", u"FD00", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u" MEZZ\u677fID", None))
        self.pushButton_eol_f193.setText(QCoreApplication.translate("Dialog", u"F193", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u" MAIN\u677fID", None))
        self.pushButton_eol_fdf6.setText(QCoreApplication.translate("Dialog", u"FDF6", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"\u603b\u6210\u53f7", None))
        self.pushButton_eol_f187.setText(QCoreApplication.translate("Dialog", u"F187", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"\u6574\u8f66\u5382\u5b9a\u4e49\u7684\u96f6\u4ef6\u53f7", None))
        self.pushButton_eol_f189.setText(QCoreApplication.translate("Dialog", u"F189", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"\u6574\u8f66\u5382ECU\u8f6f\u4ef6\u7248\u672c\u53f7", None))
        self.pushButton_eol_f089.setText(QCoreApplication.translate("Dialog", u"F089", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"\u6574\u8f66\u5382ECU\u786c\u4ef6\u7248\u672c\u53f7", None))
        self.pushButton_eol_f013.setText(QCoreApplication.translate("Dialog", u"F013", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"\u6574\u8f66\u5382\u5b9a\u4e49\u8f6f\u4ef6\u96f6\u4ef6\u53f7", None))
        self.pushButton_eol_f18a.setText(QCoreApplication.translate("Dialog", u"F18A", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"\u4f9b\u5e94\u5546\u4ee3\u7801", None))
        self.pushButton_eol_f18b.setText(QCoreApplication.translate("Dialog", u"F18B", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"ECU\u751f\u4ea7\u65e5\u671f", None))
        self.pushButton_eol_f18c.setText(QCoreApplication.translate("Dialog", u"F18C", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"ECU\u5e8f\u5217\u53f7\uff08\u6279\u6b21\u53f7/\u6d41\u6c34\u53f7\uff09", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Dialog", u"EOL DID", None))
        self.pushButton_571d_01.setText(QCoreApplication.translate("Dialog", u"\u6fc0\u6d3b", None))
        self.pushButton_571d_02.setText(QCoreApplication.translate("Dialog", u"\u672a\u6fc0\u6d3b", None))
        self.pushButton_571e_01.setText(QCoreApplication.translate("Dialog", u"\u5411\u4e0b\u641c\u7d22", None))
        self.pushButton_571e_00.setText(QCoreApplication.translate("Dialog", u"\u5411\u4e0a\u641c\u7d22", None))
        self.pushButton_571e_03.setText(QCoreApplication.translate("Dialog", u"\u67e5\u627e\u5168\u90e8", None))
        self.pushButton_571e_02.setText(QCoreApplication.translate("Dialog", u"\u6b63\u5e38\u72b6\u6001", None))
        self.label_111.setText(QCoreApplication.translate("Dialog", u"\uff08\u4e0d\u641c\u7d22\u53ef\u7528\u7ad9\u70b9\uff09", None))
        self.label_112.setText(QCoreApplication.translate("Dialog", u"\uff08\u9884\u89c8\u529f\u80fd\uff0c\u76f8\u5f53\u4e8e\u4e3b\u754c\u9762\u9884\u89c8\uff09", None))
        self.pushButton_571f_02.setText(QCoreApplication.translate("Dialog", u"\u672a\u6fc0\u6d3b", None))
        self.pushButton_571f_01.setText(QCoreApplication.translate("Dialog", u"\u6fc0\u6d3b", None))
        self.label_113.setText(QCoreApplication.translate("Dialog", u"\u8bed\u97f3\u63a7\u5236", None))
        self.label_114.setText(QCoreApplication.translate("Dialog", u"\u6536\u97f3\u673a", None))
        self.label_115.setText(QCoreApplication.translate("Dialog", u"\u5f00\u673a\u52a8\u753b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("Dialog", u"03.4.IOcontrol DID 0x2F", None))
        self.pushButton_read_f011.setText(QCoreApplication.translate("Dialog", u"Read F011\n"
"\u8bfb\u53d6\u6574\u8f66\u914d\u7f6e\u4fe1\u606f", None))
        self.label_116.setText(QCoreApplication.translate("Dialog", u"\u8f93\u5165Byte\uff1a0~165", None))
        self.lineEdit_byte.setText("")
        self.pushButton_f011_analyze.setText(QCoreApplication.translate("Dialog", u"\u5206\u6790", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("Dialog", u"03.3.Coding DID", None))
        self.pushButton_clear_log.setText(QCoreApplication.translate("Dialog", u"ClearLog", None))
        self.pushButton_save_log.setText(QCoreApplication.translate("Dialog", u"SaveLog", None))
        self.textEdit_free_input.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.pushButton_send.setText(QCoreApplication.translate("Dialog", u"Send", None))
        self.radioButton_physical.setText(QCoreApplication.translate("Dialog", u"\u7269\u7406\u5bfb\u5740", None))
        self.radioButton_functional.setText(QCoreApplication.translate("Dialog", u"\u529f\u80fd\u5bfb\u5740", None))
    # retranslateUi

